version: '3.1'

services:
  mongo:
    container_name: warering-mongoDB
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: 125478963m
      MONGO_INITDB_DATABASE: warering-project
      MONGODB_DATABASE: warering-project
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db
  emqx:
      container_name: emqx
      image: emqx:5.4.1
      restart: always

      ports:
        - 18083:18083
        - 1883:1883
        - 8083:8083
        - 8085:8081

      volumes:
        - vol-emqx-data:/opt/emqx/data
        - vol-emqx-log:/opt/emqx/log
        - ./conf/emqx.conf:/opt/emqx/etc/emqx.conf

    
      links:
        - mongo

      extra_hosts:
        - "localhost:192.168.0.6"

      environment:
        EMQX_NAME: warering-emqx
        EMQX_HOST: 127.0.0.1 

        # DEFAULT DASH PASS
        EMQX_DASHBOARD__DEFAULT_USERNAME: adminEMQX
        EMQX_DASHBOARD__DEFAULT_PASSWORD: 125478963m

        # DEFAULT APP SECRET
        EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "warering-cecret"
        EMQX_AUTH__MONGO__SERVER: "mongo:27017"
        EMQX_AUTH__MONGO__POOL: 18

  redis:
    container_name: warering-redis
    image: redis:7.2.4
    restart: always
    ports:
    - '6379:6379'

 
volumes:
  mongodb:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-log:
    name: foo-emqx-log
  vol-emqx-conf:
    name: foo-emqx-conf

