version: '3.1'

services:
  mongo:
    container_name: warering-mongoDB
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: warering-project
    ports:
      - 27018:27017
    volumes:
      - ./mongodata:/data/db

  emqx:
      container_name: emqx
      image: emqx
      restart: always

      ports:
        - 18083:18083
        - 1883:1883
        - 8083:8083
        - 8085:8081

      volumes:
        - vol-emqx-data:/opt/emqx/data
        - vol-emqx-log:/opt/emqx/log
        - ./conf/emqx.conf:/opt/emqx/etc/emqx.conf

    
      links:
        - mongo

      extra_hosts:
        - "localhost:192.168.0.6"

      environment:
        EMQX_NAME: warering-emqx
        EMQX_HOST: 127.0.0.1 

        # DEFAULT DASH PASS
        EMQX_DASHBOARD__DEFAULT_USERNAME: adminEMQX
        EMQX_DASHBOARD__DEFAULT_PASSWORD: 125478963m

        # DEFAULT APP SECRET
        EMQX_MANAGEMENT__DEFAULT_APPLICATION__SECRET: "warering-cecret"

        # EMQX_ALLOW_ANONYMOUS: "false"
        # EMQX_NOMATCH: "deny"
        # EMQX_AUTHZ__NO__MATCH: "deny"
        # EMQX_AUTHZ__DENY__ACTION: "ignore"
        # No Match Action
        # MONGO CONNECTION
        # EMQX_AUTH__MONGO__TYPE: single
        # EMQX_AUTH__MONGO__TOPOLOGY__POOL_SIZE: 1
        # EMQX_AUTH__MONGO__TOPOLOGY__MAX_OVERFLOW: 0

        EMQX_AUTH__MONGO__SERVER: "mongo:27017"
        EMQX_AUTH__MONGO__POOL: 18

        # EMQX_AUTH__MONGO__LOGIN: ""
        # EMQX_AUTH__MONGO__PASSWORD: ""
      
        # EMQX_AUTH__MONGO__DATABASE: "warering-project"
        # EMQX_AUTH__MONGO__AUTH_QUERY__COLLECTION: "deivce"

        # EMQX_AUTH__MONGO__SUPER_QUERY__COLLECTION: "emqxauthrules"
        # EMQX_AUTH__MONGO__SUPER_QUERY__SUPER_FIELD: "is_superuser"
        # EMQX_AUTH__MONGO__SUPER_QUERY__SELECTOR: "username=%u"
        # EMQX_AUTH__MONGO__SUPER_QUERY: "off"

        # EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_HASH: plain
        # EMQX_AUTH__MONGO__AUTH_QUERY__PASSWORD_FIELD: "password"
        # EMQX_AUTH__MONGO__AUTH_QUERY__SELECTOR: "username=%u"

        # # ## Enable ACL query.
        # # #Access control list
        # EMQX_AUTH__MONGO__ACL_QUERY: "on"
        # EMQX_AUTH__MONGO__ACL_QUERY__COLLECTION: "emqxauthrules"
        # EMQX_AUTH__MONGO__ACL_QUERY__SELECTOR: "username=%u"

        # EMQX_LOADED_PLUGINS: "emqx_recon,emqx_retainer,emqx_management,emqx_dashboard,emqx_auth_mongo"

        # EMQX_LISTENER__TCP__EXTERNAL__MAX_CONNECTIONS: 1000

volumes:
  mongodb-ebook:
  vol-emqx-data:
    name: foo-emqx-data
  vol-emqx-log:
    name: foo-emqx-log
  vol-emqx-conf:
    name: foo-emqx-conf

